version: 1

update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'daily'
      version_requirement_updates: 'auto'
      default_reviewers:
          - 'pgilad'
